### ISSUE TITLE
Implement families for setoid and groupoid

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/agda-groupoids#3]

**Comment by jonsterling** [comment]
I'll just put my vote here for this one :smile: 

By the way, is an `I`-family of setoids the same as an extensional function `I => SETOID`, where `SETOID` is the setoid of setoids? Or is there some more stuff that has to be dealt with?

**Comment by freebroccolo** [comment]
Essentially, yes. There's this question as to whether the families should be proof irrelevant or not but if you choose to make them proof relevant, certain constructions will fail. Palmgren talks about this but I haven't fully understood all of his examples.

[Here](https://github.com/freebroccolo/opetopic-type-theory/blob/master/models/PER.agda#L29-L75) is what they look like for PERs though. Note the `irr` field.

If you're going to use this library I think I may try to port or merge some of that stuff into this one. I created a separate repo for the semigroupoid development but now I think I'll just include it here (in a separate branch for now).

**Comment by freebroccolo** [comment]
The way I defined it in the `PER` example is actually in terms of a functor into the semicategory `PER` since this gives you some of the additional properties you need. So `I` gets lifted up a dimension first.

**Comment by jonsterling** [comment]
Ah, that's cool. Yeah, something like this would be very useful to me at the moment; I'm defining atomic sheaves and I need to express the uniqueness of a construction, and so it would be nice to have Pi and Sigma for setoids.

**Comment by freebroccolo** [comment]
Hmm, I didn't realize it but it turns out if you use a functor here, you get the `irr` field already as part of the setoid map for the functor's morphism action. See [here](https://github.com/freebroccolo/agda-groupoids/blob/8a6fe1849c2f4fa714c792238c5773bfd2862c40/src/Setoid/Fam.agda#L57-L62).
